
SELECT
    PRODUCT_CODE,
    TOTAL_SALES_AMOUNT * PRICE AS SALES
FROM 
    PRODUCT P
JOIN (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT
    FROM
        OFFLINE_SALE
    GROUP BY PRODUCT_ID
) O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY
    SALES DESC,
    PRODUCT_CODE ASC
;

